[package]
name = "parse_pdms_db"
version = "0.1.0"
edition = "2021"

#[[bin]]
#name = "shape_viewer"
#path = "src/bins/shape_viewer.rs"


#[profile.dev]
#opt-level = 0
#debug = true
#debug-assertions = true
#overflow-checks = true
#lto = false
#panic = 'unwind'
#incremental = true
#codegen-units = 256
#rpath = false

#[profile.release]
#opt-level = 3
#overflow-checks = false
#incremental = true

#[profile.release]
#debug = true
#opt-level = 2
#[profile.release]
#debug = true

[features]
default = ["compression"]  #"compression"
compression = []
web = []   #compile for just web usage, now it is too heavy now

[dependencies]
memchr = "2.5.0"
nom = "7.1.1"
lyon = "0.17.10"
nom-derive = "0.10.0"
itertools = "0.10.1"
bincode = "1.3.3"
nalgebra = "0.26.2"
nalgebra-glm = "0.12.0"
glam = { version = "0.20.2", features = ["transform-types"] }
fasteval = "0.2.4"
regex = "1.5.4"
futures = "0.3.19"
fixed = "1.12"
async-trait = "0.1.52"
approx = "0.5.1"
bitflags = "1.3.2"
derivative = "2.2.0"
concurrent-queue = "1.2.2"
instant = "0.1.12"
pollster = "0.2.5"
ordered-float = "2.10.0"
config = "0.13.1"
flate2 = "1.0.24"

highway = "0.7.0"
hash32 = "0.2.1"
hash32-derive = "0.1.1"

serde-name = "0.1.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_derive = "1.0.137"
phf = { version = "0.9", features = ["macros"] }
clap = { version = "3.1.6", features = ["derive"] }
log = "0.4.14"
rayon = "1.5.2"
tokio = { version = "1.18.2", features = ["full"] }
serde_json = { version = "1.0" }
lazy_static = "1.4.0"
cached = { version = "0.26.2", default-features = false, features = ["proc_macro"] }
dashmap = { version = "5.3.4", features = ["serde"] }
hex = "0.4.3"
notify = "4.0.17"
crossbeam-deque = "0.8.1"
crossbeam-queue = "0.3.3"
hexasphere = "7.0.0"

calamine = "0.18.0"

id_tree = { version = "1.8.0", features = ["serde_support"] }
smol_str = { version = "0.1.22", features = ["serde"] }
rand = "*"
anyhow = "1.0"
env_logger = "*"
thiserror = "*"
transmog-bincode = "0.1"

bevy = { path = "../bevy", default-features = false }
aios_core = { path = "../aios_core" }

truck-base = { version = "0.3.0",git = "https://gitee.com/happydpc/truck.git" }
truck-geotrait = { version = "0.2.0", git = "https://gitee.com/happydpc/truck.git"}
truck-geometry = { version = "0.3.0", git = "https://gitee.com/happydpc/truck.git" }
truck-polymesh = { version = "0.4.0", git = "https://gitee.com/happydpc/truck.git" }
truck-topology = { version = "0.4.0", git = "https://gitee.com/happydpc/truck.git" }
truck-modeling = { version = "0.4.0", git = "https://gitee.com/happydpc/truck.git" }
truck-meshalgo = { version = "0.2.0", git = "https://gitee.com/happydpc/truck.git" }
truck-platform = { version = "0.4.0", git = "https://gitee.com/happydpc/truck.git" }
truck-rendimpl = { version = "0.4.0", git = "https://gitee.com/happydpc/truck.git"}


prost = "0.8.0"
once_cell = "1.9.0"
dynfmt = { version = "0.1.5", features = ["curly", "python"] }


