[package]
name = "parse_pdms_db"
version = "0.1.0"
edition = "2021"

#[profile.release]
#debug = true
[profile.release]
opt-level = 2

[features]
web = []   #compile for just web usage, now it is too heavy now

[dependencies]
#nom = "7.0.0"
memchr = "2.4.1"
slab_tree = "0.3.2"
itertools = "0.10.1"
bincode = "1.3.3"
nalgebra = "0.26.2"
nalgebra-glm = "0.12.0"
glam = {version="0.20.2", features=["transform-types"]}
fasteval = "0.2.4"
regex = "1.5.4"
futures = "0.3.19"
fixed = "1.12"

#rocksdb = "0.18.0"
sanakirja = "1.2.16"

#sled = { version = "0.34.7", features = ["compression"] }
sled = { git="https://github.com/spacejam/sled.git", features = ["compression"] }

#path="../bonsaidb/crates/bonsaidb",
bonsaidb = { path="../bonsaidb/crates/bonsaidb",  version = "0.2.0", features = ["local-full",
    "client-full",
    "server-full",
    "websockets",
] }
#bonsaidb = { git = "https://github.com/khonsulabs/bonsaidb.git", default-features = false, features = "local-full" }

tinyexpr = { git = "https://github.com/AscendingCreations/tinyexpr-rs.git" }

nom = "6.1.2"
nom-derive = "0.9.0"
highway = "0.7.0"
hash32 = "0.2.1"
hash32-derive = "0.1.1"

serde-name = "0.1.1"
serde = { version = "1.0.133", features = ["derive"] }
serde_derive = "1.0.133"
phf = { version = "0.9", features = ["macros"] }
clap = "2.33.3"
mongodb = { version = "2.0.1", default-features = false, features = ["async-std-runtime"] }
log = "0.4.14"
simplelog = "0.10.0"
rayon = "1.5.1"
tokio = { version = "1.11.0", features = ["full"] }
#mysql = "21.0.2"
serde_json = { version = "1.0" }
lazy_static = "1.4.0"
static_init = "1.0.1"
cached = { version = "0.26.2", default-features = false, features = ["proc_macro"] }
dashmap =  { version="5.0.0" , features=["serde"] }
#autowired = { path = "D:/autowired-rs" }
hex = "0.4.3"
notify = "4.0.17"
crossbeam-deque = "0.8.1"
crossbeam-queue = "0.3.3"
#rug = "1.14.0"
#bevy-inspector-egui = { path = "../bevy-inspector-egui" }
#bevy = { path = "../bevy" }
bevy = { version = "0.6.1" }

id_tree = { version = "1.8.0", features=["serde_support"] }
smol_str = "0.1.21"
ncollide3d = "0.32.0"
lyon = "0.17.10"
rand = "*"
anyhow = "*"
env_logger = "*"

transmog-bincode = "0.1"

gdnative = {git="https://github.com/godot-rust/godot-rust"}

truck-base = { version = "0.2.0", path = "../truck/truck-base" }
truck-geotrait = { version = "0.1.0", path = "../truck/truck-geotrait" }
truck-geometry = { version = "0.2.0", path = "../truck/truck-geometry" }
truck-polymesh = { version = "0.3.0", path = "../truck/truck-polymesh" }
truck-topology = { version = "0.3.0", path = "../truck/truck-topology" }
truck-modeling = { version = "0.3.0", path = "../truck/truck-modeling" }
truck-meshalgo = { version = "0.1.0", path = "../truck/truck-meshalgo" }
truck-platform = { version = "0.3.0", path = "../truck/truck-platform" }
truck-rendimpl = { version = "0.3.0", path = "../truck/truck-rendimpl" }

#tonic-ws-transport = { path = "../tonic-ws-transport/transport", features = ["native"] }
#tonic = { version = "0.5.0", features = ["transport", "codegen", "prost"] }
prost = "0.8.0"
once_cell = "1.9.0"
#futures-util = "0.3.12"
#tokio-tungstenite = "0.14.0"
#tokio-stream = { version = "0.1.2", features = ["net"] }

#[build-dependencies]
#tonic-build = "0.5.0"