[package]
name = "parse_pdms_db"
version = "0.1.0"
edition = "2021"


[profile.dev]
opt-level = 0
debug = true
split-debuginfo = '...'  # Platform-specific.
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
overflow-checks = false
incremental = true

#[profile.release]
#debug = true
#opt-level = 2
#[profile.release]
#debug = true

[features]
default = ["compression"]  #"compression"
compression = []
web = []   #compile for just web usage, now it is too heavy now

[dependencies]
#nom = "7.0.0"
memchr = {git = "https://github.com/BurntSushi/memchr.git"}
slab_tree = "0.3.2"
itertools = "0.10.1"
bincode = "1.3.3"
nalgebra = "0.26.2"
nalgebra-glm = "0.12.0"
glam = { version = "0.20.2", features = ["transform-types"] }
fasteval = "0.2.4"
regex = "1.5.4"
futures = "0.3.19"
fixed = "1.12"
async-trait = "0.1.52"
approx = "0.5.1"
bitflags = "1.3.2"
derivative = "2.2.0"
concurrent-queue = "1.2.2"
#sled = { git="https://github.com/spacejam/sled.git", features = ["compression"] }

sled = { version = "0.34.7",  features = ["compression"] }


#tinyexpr = { git = "https://github.com/AscendingCreations/tinyexpr-rs.git" }
rsc = { git = "https://github.com/fivemoreminix/rsc.git" }


nom = "6.1.2"
nom-derive = "0.9.0"
highway = "0.7.0"
hash32 = "0.2.1"
hash32-derive = "0.1.1"

serde-name = "0.1.1"
serde = { version = "1.0.133", features = ["derive"] }
serde_derive = "1.0.133"
phf = { version = "0.9", features = ["macros"] }
clap = { version = "3.1.6", features = ["derive"] }
log = "0.4.14"
simplelog = "0.10.0"
rayon = "1.5.2"
#tokio = { version = "1.11.0", features = ["full"] }
#mysql = "21.0.2"
serde_json = { version = "1.0" }
lazy_static = "1.4.0"
#static_init = "1.0.2"
cached = { version = "0.26.2", default-features = false, features = ["proc_macro"] }
dashmap = { version = "5.2.0", features = ["serde"] }
#autowired = { path = "D:/autowired-rs" }
hex = "0.4.3"
notify = "4.0.17"
crossbeam-deque = "0.8.1"
crossbeam-queue = "0.3.3"
hexasphere = "7.0.0"
#rug = "1.14.0"
#bevy-inspector-egui = { path = "../bevy-inspector-egui" }
#bevy = { path = "../bevy", default-features = true }
bevy = "0.7.0"
bevy_egui = "0.13.0"
bevy-inspector-egui = "0.10.0"
#bevy_utils = { path = "../bevy/crates/bevy_utils" }
#egui = { path = "../egui/egui" }
egui = "0.17.0"

id_tree = { version = "1.8.0", features = ["serde_support"] }
smol_str = { version = "0.1.22", features = ["serde"] }
ncollide3d = "0.32.0"
lyon = "0.17.10"
rand = "*"
anyhow = "1.0"
env_logger = "*"
thiserror = "*"
#bevy_egui = { path="../bevy_egui", default-features = false, features = ["open_url"] }

transmog-bincode = "0.1"
#bevy-inspector-egui = {path = "../bevy-inspector-egui"}

truck-base = { version = "0.2.0", path = "../truck/truck-base" }
truck-geotrait = { version = "0.1.0", path = "../truck/truck-geotrait" }
truck-geometry = { version = "0.2.0", path = "../truck/truck-geometry" }
truck-polymesh = { version = "0.3.0", path = "../truck/truck-polymesh" }
truck-topology = { version = "0.3.0", path = "../truck/truck-topology" }
truck-modeling = { version = "0.3.0", path = "../truck/truck-modeling" }
truck-meshalgo = { version = "0.1.0", path = "../truck/truck-meshalgo" }
truck-platform = { version = "0.3.0", path = "../truck/truck-platform" }
truck-rendimpl = { version = "0.3.0", path = "../truck/truck-rendimpl" }


prost = "0.8.0"
once_cell = "1.9.0"
dynfmt = { version = "0.1.5", features = ["curly", "python"] }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bonsaidb = { version = "0.4.1", features = ["local-full"] }

aios_core = { path =  "../aios_core"}
