total_sync = true
incr_sync = false
project_path = "D:/AVEVA/Projects/E3D2.1"
#project_path = "E:/pdms_data_files"
#included_projects = ["sam"]
included_projects = ["APS","AMS","SCB"]
mdb_name = "ALL"
project_name = "aps"
main_db_code = 7200