total_sync = true
incr_sync = false
project_path = "/Volumes/DPC/12.1SP4Projects"
included_projects = ["Sample", "Master"]
#included_projects = ["SCB","ZNP"]
mdb_name = "Sample"
project_name = "Sample"
main_db_code = 7200