#[DbOption]
total_sync = false
incr_sync = false
#project_path = "D:/aba"
project_path = "D:/AVEVA/Plant/Projects12.1.SP4"
included_projects = ["Sample", "Master"]
#included_projects = ["ABA", "GDP"]
#included_db_files = "none"
mdb_name = "Sample"
project_name = "Sample"
main_db_code = 7200