total_sync = true
incr_sync = false
project_path = "/Volumes/DPC/12.1SP4Projects"
#project_path = "E:/pdms_data_files"
#included_projects = ["sam"]
included_projects = ["Sample", "Master"]
mdb_name = "Sample"
project_name = "Sample"
main_db_code = 7200